---
editor: source
editor_options: 
  chunk_output_type: console
---


```{r setup}
# pacman::p_load(tidyverse, rio, data.table, mgcv, marginaleffects)
pacman::p_load(tidyverse, rio)

#https://console.cloud.google.com/bigquery?ws=!1m7!1m6!12m5!1m3!1sbcs-market-dev-lake!2ssouthamerica-east1!3sb88fa74a-59b9-476a-8d05-72fcab2b99fe!2e1

source("C:/Users/GOXWW/Documents/github_edwardsmolina/spirku/spirku24/mutate_custom.R", echo=F)

theme_PH <- cowplot::theme_half_open()+
  theme(
    axis.text = element_text(size = 12),
    # axis.title = element_text(size = 14),
    legend.position = "bottom",
    legend.justification = "center",
    legend.title = element_blank())
theme_set(theme_PH)
```

## Biotech value

Import data 

```{r}
files_path <- list.files(here::here("data_valor_biotech"), full.names = TRUE)

dat <- import_list(files_path, rbind = TRUE) |>
  event_separate(geno_in=commercialName, "biotech", "plain_name")   |> 
  select(!contains("inter")) |> 
  mutate(crop_season = if_else(FIELD_pipeline=="South" & yday(FIELD_plantingDate) < yday('2023-11-15'), "Early", "Late")) |> 
    mutate(mdr=str_extract(FIELD_name, "[^_]+")) |> 
  unite("id", FIELD_plantingSeason, FIELD_name,  remove = FALSE) |> 
  rename(YLD="OBS_numValue") |>
  drop_na(commercialName)

geo_id <- dat |> distinct(id, lat=FIELD_field_latitude, lon=FIELD_field_longitude)

dat |> names()
dat |> count(OBS_observationRefCd, OBS_descriptorAbbreviation)
dat |> count(id)
dat |> count(SETS_setName)
dat |> count(biotech)
dat |> count(FIELD_plantingDate)
dat |> count(FIELD_pipeline, crop_season, mdr)
dat |> count(FIELD_plantingSeason, FIELD_pipeline, commercialName, biotech) |> data.frame()
```

Within field comparisons

 

```{r}
dat_wide <- dat |> 
  filter(OBS_observationRefCd=="GYLD") |> 
  select(id, FIELD_plantingSeason, FIELD_pipeline, mdr, SETS_setName, plain_name, biotech, YLD) |> 
  pivot_wider(names_from="biotech", values_from = "YLD", values_fn =mean) |> 
  mutate_all(~ replace(., is.null(.), NA)) |> 
  data.frame() |> 
  # filter(TRE>0)
  rowwise() |> 
  mutate(PRO4_RR=PRO4-RR2, 
         TRE_PRO3=TRE-VT3P) |> 
  filter(!(FIELD_pipeline=="South" & mdr =="CSALO9"))

dat_wide |> 
  # slice(1:30) |> data.frame()
export(here::here("data_valor_biotech", "data_wide.xlsx"))
```

PRO4 value

```{r}
dat_wide |> 
  filter(PRO4_RR>-20) |> 
  filter(!mdr=="GFXVN") |> 
  ggplot() + 
  aes(x=factor(FIELD_plantingSeason),y=PRO4_RR)+
  facet_wrap(vars(FIELD_pipeline,mdr)) + 
  geom_boxplot(width=0.2, fill="grey70") + 
  geom_point(alpha=.2) + 
  stat_summary(aes(label=round(..y..)), col="red", 
               fun=median, geom="text", size=3, hjust = 2.2)   + 
  labs(title="PRO4 - value",
       subtitle="Calculated as within field YLD difference (qq) against same genotipe with RR2 biotech",
       y="qq", 
       x="Planting season")
```

```{r}
dat_wide |> 
  filter(PRO4_RR>-20) |> 
  filter(!mdr=="GFXVN") |> 
  ggplot() + 
  aes(x=factor(FIELD_plantingSeason),y=PRO4_RR)+
  facet_wrap(vars(FIELD_pipeline)) + 
  geom_boxplot(width=0.1, fill="grey70") + 
  geom_point(alpha=.2) + 
  stat_summary(aes(label=round(..y..)), col="red", 
               fun=median, geom="text", size=4, hjust = 2.2)   + 
  labs(title="PRO4 - value",
       subtitle="Calculated as within field YLD difference (qq) against same genotipe with RR2 biotech",
       y="qq", 
       x="Planting season")
```

TRE Value

```{r}
dat_wide |> 
  filter(TRE_PRO3>-20) |> 
  filter(!mdr=="GFXVN") |> 
  ggplot() + 
  aes(x=factor(FIELD_plantingSeason),y=TRE_PRO3)+
  facet_wrap(vars(FIELD_pipeline,mdr)) + 
  geom_boxplot(width=0.2, fill="grey70") + 
  geom_point(alpha=.2) + 
  stat_summary(aes(label=round(..y..)), col="red", 
               fun=median, geom="text", size=3, hjust = 2.1) +   
   labs(title="TRECEPTA value",
       subtitle="Calculated as within field YLD difference (qq) against same genotipe with VT3P biotech",
       y="qq", 
       x="Planting season")
```

```{r}
dat_wide |> 
  filter(TRE_PRO3>-20) |> 
  filter(!mdr=="GFXVN") |> 
  ggplot() + 
  aes(x=factor(FIELD_plantingSeason),y=TRE_PRO3)+
  facet_wrap(vars(FIELD_pipeline)) + 
  geom_boxplot(width=0.2, fill="grey70") + 
  geom_point(alpha=.2) + 
  stat_summary(aes(label=round(..y..)), col="red", 
               fun=median, geom="text", size=3, hjust = 3) +   
   labs(title="TRECEPTA value",
       subtitle="Calculated as within field YLD difference (qq) against same genotipe with VT3P biotech",
       y="qq", 
       x="Planting season")
```

Biotech value ~ lat or lon  

```{r}
dat_wide |> 
  # filter(PRO4_RR>-20) |> 
  filter(!mdr=="GFXVN") |> 
  left_join(geo_id) |>  
  pivot_longer(PRO4_RR:TRE_PRO3)  |> 
  drop_na(value) |> 
  filter(value>-20) |> 
  ggplot() + 
  facet_wrap("name") +
  aes(x=lon, y=value, col=factor(FIELD_plantingSeason)) +
  geom_point(alpha=.2) + 
  geom_smooth(span=.7) + 
  labs(title="Valor Biotech ~ longitud", 
       x="Longitud", y="qq")
```

```{r}
dat_wide |> 
  # filter(PRO4_RR>-20) |> 
  filter(!mdr=="GFXVN") |> 
  left_join(geo_id) |>  
  pivot_longer(PRO4_RR:TRE_PRO3)  |> 
  drop_na(value) |> 
  filter(value>-20) |> 
  ggplot() + 
  facet_wrap("name") +
  aes(x=lat, y=value, col=factor(FIELD_plantingSeason)) +
  geom_point(alpha=.2) + 
  geom_smooth(span=.7) + 
  labs(title="Valor Biotech ~ latitud", 
       x="Longitud", y="qq")
```

## Damage

```{r}
files_path_dam <- list.files(here::here("data_biotech_damage"), full.names = TRUE)

dam <- import_list(files_path_dam, rbind = TRUE) |>
  event_separate(geno_in=commercialName, "biotech", "plain_name")   |> 
  select(!contains("inter")) |> 
  mutate(crop_season = if_else(FIELD_pipeline=="South" & yday(FIELD_plantingDate) < yday('2023-11-15'), "Early", "Late")) |> 
    mutate(mdr=str_extract(FIELD_name, "[^_]+")) |> 
  unite("id", FIELD_plantingSeason, FIELD_name,  remove = FALSE) |> 
  # rename(YLD="OBS_numValue") |>
  drop_na(commercialName)

geo_id_dam <- dam |> distinct(id, lat=FIELD_field_latitude, lon=FIELD_field_longitude)

dam |> names()
dam |> count(OBS_observationRefCd, OBS_descriptorAbbreviation)
dam |> count(id)
dam |> count(SETS_setName)
dam |> count(biotech)
dam |> count(FIELD_pipeline, crop_season, mdr)
dam |> count(FIELD_plantingSeason, FIELD_pipeline, commercialName, biotech) |> data.frame()
```

## Spodoptera

```{r}
dam_wide <- dam |>
  select(id, FIELD_plantingSeason, FIELD_pipeline, mdr, SETS_setName, plain_name, biotech, OBS_numValue) |> 
  pivot_wider(names_from="biotech", values_from = "OBS_numValue", values_fn =mean) |> 
  mutate_all(~ replace(., is.null(.), NA)) |> 
  data.frame() |> 
  # filter(TRE>0)
  rowwise() |> 
  mutate(PRO4_efic=(1-(PRO4/RR2))*100, 
         TRE_efic=(1-(TRE/RR2)*100)) |> 
  filter(!(FIELD_pipeline=="South" & mdr =="CSALO9"))

dam_wide |> export(here::here("data_valor_biotech", "data_wide.xlsx"))
```

```{r}
dam |>
  filter(str_detect(biotech, "PRO$|RR2|TRE|VT3P"))|>  
  ggplot() + 
  aes(y=OBS_numValue, x=factor(FIELD_plantingSeason))+
  facet_grid(FIELD_pipeline~biotech) + 
  geom_boxplot(width=0.2, fill="grey70") +
  geom_point(alpha=.2) + 
  stat_summary(aes(label=round(..y..)), col="red",
               fun=median, geom="text", size=5, hjust = 2.2)   +
  labs(title="Spodoptera Frugiperda - Vegetative Damage", 
       y="% of plants with damage Davis>3", 
       x="Planting season")
```

### Ear Damage #############
```{r}
ear<-c("DAEAR","HZ9","SF9")

df3<-biotech %>% filter(trait %in% ear)
```