---
title: "Da침o Spodoptera "
editor_options: 
  chunk_output_type: console
---

## Session setup

```{r setup}
pacman::p_load(tidyverse)
# pacman::p_load(tidyverse) # only explore after querying 
# conflicted::conflict_prefer("filter", "dplyr")
```

```{r}
biotech_conosur <- readr::read_csv("data/biotech_conosur_2024-06-26.csv")
dat <- readr::read_csv("data/plagas_conosur_23.csv")
# biotech_conosur %>% count(FIELD_plantingSeason)
```

## Spodoptera

```{r}
spod <- dat %>% 
  # count(FIELD_plantingDate, OBS_observationRefCd) %>% 
  filter(str_detect(OBS_observationRefCd, "DSSF|SF9")) %>% 
  unite("trait", OBS_observationRefCd, OBS_descriptorAbbreviation, remove = F) %>% 
  mutate(FIELD_planting_month = format_ISO8601(as.Date(FIELD_plantingDate), precision = "ym")) 
```

```{r eval=FALSE}
hibs <- c("DK7272TRE", "DK7210PRO4", "DK7210RR2", "DK7272VT3P", "NEXT226PWUE", "NK842VIPTERA3")

spod %>% 
  filter(commercialName %in% hibs) %>% 
  ggplot()+
  aes(y=commercialName, x=OBS_numValue) +
  geom_boxplot(alpha=.5) +
  geom_point(alpha=.5, height =.1) + 
  facet_grid(.~trait) 
```

```{r}
spod %>%
  filter(str_detect(trait, "DSSFP")) %>% 
  filter(commercialName == "DK7210RR2") %>% 
  group_by(FIELD_name, FIELD_planting_month) %>% 
  summarise(OBS_numValue_RR = max(OBS_numValue)) -> field_dam_level 
```

```{r}
field_dam_level %>% 
  left_join(spod %>%
  filter(str_detect(trait, "DSSFP")) %>%
  select(FIELD_name, FIELD_planting_month, lat=FIELD_field_latitude, lon=FIELD_field_longitude, commercialName, OBS_numValue) %>% 
  event_separate(geno=commercialName, "biotech", "hybrid") %>% 
  filter(commercialName %in% hibs) ) %>% 
  rio::export("data/spod_veg_23.xlsx")
```

```{r}
spod_veg <- rio::import("data/spod_veg_23.xlsx")
```

```{r}
spod_veg %>% 
  # count(dam_level,commercialName)
  ggplot() + 
  # facet_wrap("FIELD_planting_month") + 
  aes(x=FIELD_planting_month, y=OBS_numValue,
      col=commercialName, group=commercialName) + 
      # label=paste0(round(OBS_numValue), "\nn=", n)
  geom_point() + 
  stat_summary(geom="line", fun.y="mean", size=1)+
  theme(legend.position='bottom') + 
  labs(x="FIELD_Planting_month", y="% de da침o Davis >=3") 


ggsave(last_plot(), w=5.5, h=5.5, file="plots/spod_veg_month.png", scale=1.3)
```


```{r}
field_dam_level %>% 
  left_join(spod %>% 
  filter(str_detect(trait, "DSSFP")) %>% 
  filter(str_detect(commercialName, "7272|7210")))%>% 
  filter(!str_detect(commercialName, "RR"))%>% 
  ggplot() + 
  aes(x=OBS_numValue_RR, y= OBS_numValue,
      col=commercialName) + 
  geom_point() + 
  geom_smooth() + 
  labs(x="Presi칩n en RR2", y="% de da침o Davis >=3") + 
  theme(legend.position='bottom')

ggsave(last_plot(), w=4, h=4, file="plots/spod_veg_press.png", scale=1.3)
```


### Ear Damage

```{r}
biotech_conosur %>% 
  # count(FIELD_plantingDate, OBS_observationRefCd) %>% 
  # filter(str_detect(commercialName, "7272")) %>% 
  mutate(month_y = format_ISO8601(as.Date(FIELD_plantingDate), precision = "ym")) %>%
 # count(trait)
  filter(commercialName %in% hibs) %>% 
  filter(str_detect(trait, "SF9_SUB")) %>% 
 select(FIELD_plantingSeason, FIELD_name, FIELD_planting_month=month_y, lat=FIELD_field_latitude, lon=FIELD_field_longitude, commercialName, OBS_numValue) %>% 
  event_separate(geno=commercialName, "biotech", "hybrid") %>% 
  rio::export("data/spod_ear_23.xlsx")
```

```{r eval=FALSE}
ear_damage <-   rio::import("data/spod_ear_23.xlsx")

ear_damage %>% 
  ggplot()+
  aes(y=OBS_numValue, commercialName) +
  geom_violin(alpha=.5) + 
  geom_jitter(alpha=.5, height =.1) + 
  facet_grid(.~ FIELD_plantingSeason, scales="free")
```

# valor Biotech
```{r eval=FALSE}
dat %>% count(trait)
  filter(OBS_numValue>100) %>% 
  select(FIELD_Country, FIELD_year, FIELD_name, OBS_code, OBS_numValue)
```


## Diatraea

Nro de orificios por tallo

```{r}
dia <- dat %>% 
  # count(FIELD_plantingDate, OBS_observationRefCd) %>% 
  filter(str_detect(OBS_observationRefCd, "NOHAS")) # %>% mutate(RDR_damage_class=NA, EAR_damage_class=NA)
```

```{r eval=FALSE}
hibs <- c("DK7272TRE", "DK7210PRO4", "DK7210RR2", "DK7272VT3P", "NEXT226PWUE", "NK842VIPTERA3")

dia %>% 
#   filter(commercialName %in% "DK7210RR2") %>% 
# count(OBS_numValue)
  # filter(commercialName %in% hibs) %>% 
  ggplot()+
  aes(y=commercialName, x=OBS_numValue) +
  geom_boxplot(alpha=.5) +
  geom_jitter(alpha=.5, height =.1) + 
  facet_grid(.~OBS_observationRefCd)
```
 > hacer mapa


















```{r}
spod_veg %>% 
  pivot_wider(names_from = OBS_code, 
              values_from = OBS_numValue)-> spod_wide
```


```{r}
field = "ATUCK1_QUIMILI_RYK_F"	
season = "2020"	
hyb =	"DK7210VT3P"

biotech %>% 
  filter(FIELD_name==field, FIELD_plantingSeason==season, commercialName==hyb) %>% 
  select(FIELD_name, FIELD_plantingSeason, commercialName, OBS_code, OBS_numValue) %>% 
  arrange(OBS_code)
```

```{r}
pull(DSSFN)
  ggplot()+
  aes(x=DSSFN, y=DSSFP) +
  geom_point(alpha=.5) + 
  facet_grid(FIELD_Country~ FIELD_plantingSeason, scales="free")
```

```{r eval=FALSE}
spod_veg %>% 
  filter(OBS_numValue>100) %>% 
  select(FIELD_Country, FIELD_plantingSeason, FIELD_name, OBS_code, OBS_numValue)

field1 = "ATUCK1_RIOMUERTO_VICENTIN_F"	
season1 = "2020"	
# hyb =	"DK7210VT3P"

spod_veg %>% 
  filter(FIELD_name==field1, FIELD_plantingSeason==season1) %>% 
  select(FIELD_Country, FIELD_plantingSeason, FIELD_name, OBS_code, OBS_numValue) %>% 
  arrange(OBS_code) %>% 
  data.frame
```

```{r}
spod_veg %>% 
  filter(OBS_code=="DSSFN", FIELD_year==2023) %>% 
  select(FIELD_Country, FIELD_year, FIELD_name, OBS_code, OBS_numValue) %>% 
  data.frame

```

