---
title: "Biotechs Conosur"
editor_options: 
  chunk_output_type: console
---

```{r setup}
pacman::p_load(tidyverse)
# pacman::p_load(tidyverse) # only explore after querying 
# conflicted::conflict_prefer("filter", "dplyr")
hibs <- c("DK7272TRE","DK7272VT3P", 
          "DK7210PRO4", "DK7210RR2",  
          "NEXT226PWUE", "NK842VIPTERA3")

```


```{r}
dat %>% 
  # count(trait) 
  filter(commercialName %in% hibs) %>%   
  filter(trait %in% c("DSSFP","SF9","NOHAS.DIATSA","DAEAR")) %>%
  # filter(trait %in% c("DSSFP")) %>% 
  ggplot() + 
  aes(x=FIELD_plantingSeason, y=OBS_numValue) + 
  geom_point() +
  stat_summary(aes(colour=commercialName), fun.y=mean, geom="line", size=1.1) +
  facet_wrap("trait", scale = "free")
```


```{r}
dat %>% 
  filter(commercialName %in% c("DK7272TRE","DK7272VT3P", "DK7210PRO4", "DK7210RR2")) %>%   
  filter(trait %in% c("YLD")) %>% 
  ggplot() + 
  aes(x=createdTechnology, y=OBS_numValue) + 
  geom_line(aes(group=year_loc), alpha=.1)+
  stat_summary(aes(group=1), fun.y=mean, geom="line", size=1.1, col="red") +
  geom_point() + 
  facet_grid(crop_season ~ base_gen, scales = "free") + 
  theme_bw() +
  stat_summary(fun = "mean", colour = "blue", size = 6,
                 geom = "text", aes(label = round(after_stat(y), 0)),
                 position = position_nudge(x = 0.1))
```

```{r}
dat %>% names
```

## Spodoptera veg

```{r}
dat %>% 
  # filter(commercialName %in% c("DK7272TRE","DK7272VT3P", "DK7210PRO4", "DK7210RR2")) %>%   
  filter(trait %in% c("DSSFP")) %>% 
  ggplot() + 
  aes(x=createdTechnology, y=OBS_numValue) + 
  # geom_line(aes(group=year_loc), alpha=.1)+
  # stat_summary(aes(group=1), fun.y=mean, geom="line", size=1.1, col="red") +
  geom_boxplot() + 
  geom_point() + 
  facet_grid(crop_season ~ ., scales = "free") + 
  theme_bw() +
  stat_summary(fun = "mean", colour = "blue", size = 6,
                 geom = "text", aes(label = round(after_stat(y), 0)),
                 position = position_nudge(x = 0.1))

```

## Daño en espiga

```{r}
dat %>% 
  # filter(commercialName %in% c("DK7272TRE","DK7272VT3P", "DK7210PRO4", "DK7210RR2")) %>%   
  filter(trait %in% c("SF9", "HZ9", "DAEAR")) %>% 
  ggplot() + 
  aes(x=createdTechnology, y=OBS_numValue, col=trait) + 
  # geom_line(aes(group=year_loc), alpha=.1)+
  # stat_summary(aes(group=1), fun.y=mean, geom="line", size=1.1, col="red") +
  geom_boxplot( aes(fill = trait), alpha=.1, 
                position = position_dodge(width = 0.7)) + 
  # geom_point() + 
  facet_grid(crop_season ~ trait, scales = "free_y") + 
  theme_bw() +
  stat_summary(fun = "mean", size = 6,
               geom = "text", 
               aes(label = round(after_stat(y), 1)),
               position = position_dodge(width = 0.7)) + 
  lims(y=c(0,25))

```

## Diatraea

```{r}
dat %>% 
  # count(trait)
  # filter(commercialName %in% c("DK7272TRE","DK7272VT3P", "DK7210PRO4", "DK7210RR2")) %>%   
  filter(trait %in% c("NOHAS.DIATSA")) %>% 
  data.frame
  ggplot() + 
  aes(x=commercialName, y=OBS_numValue) + 
  # geom_line(aes(group=year_loc), alpha=.1)+
  # stat_summary(aes(group=1), fun.y=mean, geom="line", size=1.1, col="red") +
  geom_boxplot() + 
  geom_point() + 
  facet_grid(crop_season ~ ., scales = "free") + 
  theme_bw() +
  stat_summary(fun = "mean", colour = "blue", size = 6,
                 geom = "text", aes(label = round(after_stat(y), 0)),
                 position = position_nudge(x = 0.1))

```




```{r eval=FALSE}
spo %>% count(FIELD_plantingSeason) 
```

```{r}
spo %>% 
  # count(FIELD_plantingSeason, OBS_observationRefCd) %>% 
  group_by(FIELD_name, commercialName, SUB, trait) %>% 
  summarise(OBS_numValue = mean(OBS_numValue)) %>% 
  pivot_wider(names_from = SUB, values_from = OBS_numValue) %>% 
  mutate(dif=`NA`-SUB) %>% 
  # filter(trait=="HZ9") %>% 
  # filter(FIELD_pipeline == "South") %>% 
  ggplot() + 
  facet_wrap("FIELD_name", scales = "free") + 
  aes(OBS_observationRefCd, OBS_numValue, 
      group=commercialName) + 
  geom_point() + 
  geom_line() +
  # scale_x_continuous(breaks=scales::pretty_breaks(10)) + 
  theme(axis.text.x=element_text(angle=60, hjust=.5))
```

```{r}
spod <- dat %>% 
  filter(str_detect(trait, "DSSFP|SF9_SUB")) 
```

```{r eval=FALSE}


spod %>% 
  filter(commercialName %in% hibs) %>% 
  ggplot()+
  aes(y=commercialName, x=OBS_numValue) +
  geom_boxplot(alpha=.5) +
  geom_point(alpha=.5, width =.1) + 
  facet_grid(.~trait)+
  scale_x_continuous(breaks=scales::pretty_breaks(6))
```

## Diatraea

```{r}
pla <- readr::read_csv("data/otras_23.csv") %>% 
    separate(OBS_observationRefCd, into=c("trait", "SUB"), 
             remove = T) 
```

Nro de orificios por tallo

```{r}
diat <- pla %>%  
  filter(str_detect(trait, "NOHAS"))  
  # mutate(RDR_damage_class=NA, EAR_damage_class=NA)
```

```{r eval=FALSE}
diat %>% 
  # filter(commercialName %in% "DK7210RR2") %>%
# count(OBS_numValue)
  # filter(FIELD_plantingSeason %in% 2023) %>%
  # filter(FIELD_name %in% "DBORE_ELARANADO_SIMEONI_LATE_F23") %>% 
  select(commercialName, trait, OBS_numValue) %>% 
  # count(OBS_numValue)
  ggplot()+
  # facet_wrap("FIELD_plantingSeason") +
  aes(y=commercialName, x=OBS_numValue) +
  # geom_line(aes(group=commercialName)) +
  # geom_boxplot(alpha=.5) +
  geom_point(alpha=.5, height =.1) #  
  # facet_grid(.~trait)
```

> hacer mapa

# Daño de espiga no reconocido

```{r}
daear <- pla %>% 
  filter(str_detect(trait, "DAEAR")) 
```

```{r}
daear %>% 
  ggplot()+
  aes(commercialName, OBS_numValue) + 
  facet_wrap("FIELD_plantingSeason") +
  geom_point() 
```

```{r eval=FALSE}
daear %>% 
  filter(commercialName %in% "DK7210RR2") %>%
# count(OBS_numValue)
  # filter(FIELD_plantingSeason %in% 2023) %>%
  # filter(FIELD_name %in% "DBORE_ELARANADO_SIMEONI_LATE_F23") %>%
  # select(commercialName, trait, OBS_numValue) %>%
  # count(OBS_numValue)
  ggplot()+
  facet_wrap("FIELD_plantingSeason") +
  aes(y=OBS_numValue, x=trait) +
  # facet_grid(.~trait) +
  geom_line(aes(group=interaction(FIELD_name, commercialName))) +  
  geom_point(alpha=.5) #
  # geom_boxplot(alpha=.5) +
```


```{r}
spod_veg %>% 
  pivot_wider(names_from = OBS_code, 
              values_from = OBS_numValue)-> spod_wide
```


```{r}
field = "ATUCK1_QUIMILI_RYK_F"	
season = "2020"	
hyb =	"DK7210VT3P"

biotech %>% 
  filter(FIELD_name==field, FIELD_plantingSeason==season, commercialName==hyb) %>% 
  select(FIELD_name, FIELD_plantingSeason, commercialName, OBS_code, OBS_numValue) %>% 
  arrange(OBS_code)
```

```{r}
pull(DSSFN)
  ggplot()+
  aes(x=DSSFN, y=DSSFP) +
  geom_point(alpha=.5) + 
  facet_grid(FIELD_Country~ FIELD_plantingSeason, scales="free")
```

```{r eval=FALSE}
spod_veg %>% 
  filter(OBS_numValue>100) %>% 
  select(FIELD_Country, FIELD_plantingSeason, FIELD_name, OBS_code, OBS_numValue)

field1 = "ATUCK1_RIOMUERTO_VICENTIN_F"	
season1 = "2020"	
# hyb =	"DK7210VT3P"

spod_veg %>% 
  filter(FIELD_name==field1, FIELD_plantingSeason==season1) %>% 
  select(FIELD_Country, FIELD_plantingSeason, FIELD_name, OBS_code, OBS_numValue) %>% 
  arrange(OBS_code) %>% 
  data.frame
```

```{r}
spod_veg %>% 
  filter(OBS_code=="DSSFN", FIELD_year==2023) %>% 
  select(FIELD_Country, FIELD_year, FIELD_name, OBS_code, OBS_numValue) %>% 
  data.frame

```

### Ear Damage

```{r}
ear_damage <- biotech %>% 
  filter(str_detect(OBS_code, "DAEAR|HZ9|SF9")) %>%
  filter(str_detect(OBS_code, "SUB")) # %>%
  # mutate(EAR_damage_class =
  #          cut(OBS_numValue, 
  #              breaks=c(-Inf, 0.01, 2, 4, Inf), 
  #              labels=c("No Damage","Low Damage","Medium Damage","High Damage"))
         # ) # %>% filter(!is.na(EAR_damage_class))
```

```{r eval=FALSE}
ear_damage %>% 
  ggplot()+
  aes(x=OBS_numValue, OBS_code, col=OBS_code) +
  geom_violin(alpha=.5) + 
  geom_jitter(alpha=.5, height =.1) + 
  facet_grid(FIELD_Country~ FIELD_year, scales="free")
```

```{r eval=FALSE}
ear_damage %>% 
  filter(OBS_numValue>100) %>% 
  select(FIELD_Country, FIELD_year, FIELD_name, OBS_code, OBS_numValue)
```

